{
 "title": "Zipkin",
 "description": "Visualize Prometheus metrics exported by OpenZipkin (http://zipkin.io/).",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Number of Span",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "zipkin_collector_spans_total{transport=\"http\",}"
    }
   ]
  },
  {
   "title": "Messages bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "zipkin_collector_message_bytes{transport=\"http\",}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\",id=\"Tenured Gen\",}"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_load_average_1m" }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_live_threads" }
   ]
  },
  {
   "title": "Drop message",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "zipkin_collector_messages_dropped_total"
    },
    { "expr": "gc_copy_time" },
    { "expr": "gc_marksweepcompact_count" },
    { "expr": "gc_marksweepcompact_time" }
   ]
  }
 ]
}