apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: prometheus
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`grafana.minikube`)
      kind: Rule
      services:
      - name: prometheus-grafana
        port: 80
        namespace: prometheus